### ISSUE TITLE
please clean source for missing function

### ISSUE THREAD

**Issue by sriramab** [tpgjs66/cchaidR#2]
```r
Error in eval(expr, envir, enclos) : could not find function "ff"
Error : unable to load R code in package ‘cchaid’
ERROR: lazy loading failed for package ‘cchaid’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/cchaid’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/cchaid’
Installation failed: Command failed (1)
```

This is the error reported by R. You should first check with tools in Rstudio that you package pass all tests. 

Here the problem is function ff. 

This does not allow the new version be installed and R goes back to previous cchaid version.

**Comment by sriramab** [comment]
sorry my fault. it was a conflict with my cchaid :)

**Comment by tpgjs66** [comment]
Hi Sri,

It's good to have a working package now.

Also I will send a question to you for ur colleage.

나의 iPhone에서 보냄

2017. 6. 10. 오전 11:23 Srirāma Bhamidipāti <notifications@github.com> 작성:
